"""Every statistic-shaped literal in the paper must be a generated macro or a declared design constant."""
import re
from pathlib import Path

import pytest

PAPER = Path(__file__).resolve().parents[1] / "paper"
_NUMBER = re.compile(r"(?<![\w\\{.])\d[\d,{}]*\.\d+|(?<![\w\\{])\d{1,3}(?:\{?,\}?\d{3})+|(?<![\w\\{])\d+\\?%")

# Design constants fixed in PREREG.md / PREREG_ADDENDUM.md, citation locators, and
# Krippendorff's thresholds. Nothing here is a measured result.
DESIGN = {
    "0.667", "0.800", "0.50", "0.2", "0.9", "0.03", "0.05", "1.96", "2.58", "4.5", "0.10",
    "0.5", "100\\%", "2.0", "4.0", "5.5",   # alpha grid point; "not 100%"; licence/model names
    "1,000", "5,000", "6,000", "80%", "95%", "30%", "80\\%", "95\\%", "30\\%", "1{,}000", "6{,}000", "5{,}000",
}


def _literals(tex: str) -> set[str]:
    tex = re.sub(r"(?<!\\)%.*", "", tex)                 # comments
    tex = re.sub(r"\\(cite[pt]?|ref|label|input|includegraphics|usepackage|documentclass|setlength|sisetup)(\[[^\]]*\])*\{[^}]*\}", "", tex)
    tex = re.sub(r"\\(begin|end)\{[^}]*\}(\{[^}]*\})?", "", tex)
    return {m.group(0) for m in _NUMBER.finditer(tex)}


@pytest.mark.parametrize("name", ["main.tex", "short.tex", "judges_section.tex", "appendix.tex"])
def test_no_untraced_numbers(name):
    path = PAPER / name
    if not path.exists():
        pytest.skip(f"{name} not written yet")
    extra = sorted(_literals(path.read_text()) - DESIGN)
    assert not extra, f"{name}: literal numbers not generated by scripts/paper_numbers.py: {extra}"
